stages:
  - policy

enforce-dev-mr:
  stage: policy
  image: bash:5.2
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - when: never
  script:
    - bash scripts/enforce-dev-mr.sh
